---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bfboin

<!-- badges: start -->
<!-- badges: end -->

The goal of bfboin is to provide an independent implementation of the [BF-BOIN design](https://pubmed.ncbi.nlm.nih.gov/38048044/) aiming to reproduce the functionality of the [shiny app by MD Anderson](https://biostatistics.mdanderson.org/shinyapps/BF-BOIN/).

## Installation

You can install the development version of bfboin like so:

``` r
# install.packages("devtools")
devtools::install_gitlab("boin/bfboin")
```


## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(bfboin)
## basic example code
get.oc.bf(ntrial = 100,
          seed = 9,
          target = 0.25,
          p.true = c(0.1, 0.5),
          ncohort = 10,
          cohortsize = 3,
          n.earlystop = 9,
          startdose = 1,
          titration = FALSE,
          cutoff.eli = 0.95,
          extrasafe = TRUE,
          offset = 0.1,
          boundMTD=FALSE,
          n.cap = 12,
          end.backfill = TRUE,
          n.per.month = 1,
          dlt.window = 1,
          p.response.true = c(0.001, 0.001))
```
